### ISSUE TITLE
Build project info card using using available info from github API - ex: https://api.github.com/repos/shescoding/projects-platform-frontend

### ISSUE THREAD

**Issue by nurmerey** [shescoding/projects-platform-frontend#2]
Todos:
- [x] create components to support the UI for the project info card #3 
- [x] Figure out which GitHub API is needed for this and overall information architecture for the page
- [x] preliminary API integration with UI component
- [x] coordinate with backend to figure out data persistence
- [x] screenshot and expected behavior
- [x] add tests

**Comment by nurmerey** [comment]
This is done.
